clear all, close all;
img_1 = imread('test1.jpg');
img_2 = imread('test2.jpg');
[img_height, img_width,img_tun] = size(img_1);
[left_eye1, right_eye1] = myhough2(img_1);
[left_eye2, right_eye2] = myhough2(img_2);
[left_mouth1, right_mouth1] = mouthCorner(left_eye1, right_eye1, img_1);
[left_mouth2, right_mouth2] = mouthCorner(left_eye2, right_eye2, img_2);
first_control_group_x = [1 right_eye1(1) left_mouth1(1) img_height;
                         1 right_eye1(1) left_mouth1(1) img_height;
                         1 left_eye1(1) right_mouth1(1) img_height;
                         1 left_eye1(1) right_mouth1(1) img_height];
first_control_group_y = [1 right_eye1(2) left_eye1(2) img_width;
                         1 right_eye1(2) left_eye1(2) img_width;
                         1 left_mouth1(2) right_mouth1(2) img_width;
                         1 left_mouth1(2) right_mouth1(2) img_width];
second_control_group_x = [1 right_eye2(1) left_mouth2(1) img_height;
                         1 right_eye2(1) left_mouth2(1) img_height;
                         1 left_eye2(1) right_mouth2(1) img_height;
                         1 left_eye2(1) right_mouth2(1) img_height];
second_control_group_y = [1 right_eye2(2) left_eye2(2) img_width;
                         1 right_eye2(2) left_eye2(2) img_width;
                         1 left_mouth2(2) right_mouth2(2) img_width;
                         1 left_mouth2(2) right_mouth2(2) img_width];
